name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event.head_commit.message == 'k8s deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k8s

    
      

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "v1.24.0"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name hr-stag-eksdemo1 --region ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Get latest image tag from ECR
      id: get-tag
      run: |
        TAG=$(aws ecr describe-images \
          --repository-name ${{ secrets.ECR_REPO_NAME }} \
          --region ${{ secrets.AWS_DEFAULT_REGION }} \
          --query 'sort_by(imageDetails,& imagePushedAt)[-1].imageTags[0]' \
          --output text)
        IMAGE_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.AWS_ACCOUNT_ID }}:$TAG"
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Inject image URI into manifest
      run: |
        sed -i "s|image:.*|image: $IMAGE_URI|" deployment.yml
        cat deployment.yml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yml && kubectl apply -f svc.yml
