name: Terraform Destroy

on:
  push:
    branches: [main]

jobs:
  terraform:
    if: startsWith(github.event.head_commit.message, 'terraform destroy')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Empty ECR repository before destroy
      run: |
        REPO_NAME=${{ secrets.ECR_REPO_NAME }}
        REGION=${{ secrets.AWS_DEFAULT_REGION }}

        IMAGE_IDS=$(aws ecr list-images --repository-name $REPO_NAME --region $REGION --query 'imageIds[*]' --output json)

        if [[ "$IMAGE_IDS" != "[]" ]]; then
          echo "🧹 Deleting all images in ECR repo: $REPO_NAME"
          aws ecr batch-delete-image --repository-name $REPO_NAME --region $REGION --image-ids "$IMAGE_IDS"
        else
          echo "✅ No images to delete in ECR"
        fi

    - name: Terraform Init & Destroy
      run: |
        terraform init
        terraform destroy --auto-approve
